const SUPABASE_URL = 'https://qwstnlmoqgfkxmxykgfv.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3c3RubG1vcWdma3hteHlrZ2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mzg2MjEsImV4cCI6MjA2ODIxNDYyMX0.FyWXQk8ZJMBny_XZewPdQDvpZVQ0CpIZET5FUz3IE7o';
const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
export default supabase;
